version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: frontend
          command: |
            cd ./frontend
            pwd
            ls
      - run: npm i 
      - run: npm run lint
workflows:
  default:
    jobs:
      - build
